import Link from "next/link";
import { ArrowLeft, Play, Video } from "lucide-react";
import { GALLERY, type GalleryEntry } from "@/lib/gallery";
import { listCompletedJobs } from "@/lib/jobs";

export const metadata = {
  title: "Gallery — LeadFlow",
  description: "All personalized outbound videos generated by LeadFlow.",
};

// Always render fresh — new generations should appear immediately on reload.
export const revalidate = 0;

const ACCENTS = ["#DC2626", "#F87171", "#991B1B", "#7c1d6f", "#1f3a5f", "#374151"];

async function getEntries(): Promise<GalleryEntry[]> {
  const jobs = (await listCompletedJobs(20)) ?? [];
  const dynamic: GalleryEntry[] = jobs.map((j, i) => {
    const lead = j.lead;
    const firstName = lead?.firstName ?? lead?.fullName ?? "Prospect";
    const fullName = lead?.fullName ?? firstName;
    return {
      id: `job-${j.jobId}`,
      name: fullName,
      role: lead?.role ?? "—",
      company: lead?.company?.name ?? j.input?.input?.value ?? "—",
      stat: j.heygenDuration
        ? `${Math.round(j.heygenDuration)}s · ${j.wordCount ?? "personalized"}-word script`
        : "Personalized outbound video",
      accent: ACCENTS[i % ACCENTS.length],
      videoUrl: j.outputUrl,
    };
  });
  const dynamicCompanies = new Set(
    dynamic.map((d) => d.company?.toLowerCase()).filter(Boolean)
  );
  const seed = GALLERY.filter(
    (s) => !dynamicCompanies.has(s.company?.toLowerCase())
  );
  return [...dynamic, ...seed];
}

export default async function GalleryPage() {
  const entries = await getEntries();
  return (
    <main className="relative min-h-screen w-full overflow-x-hidden">
      <div className="grain" aria-hidden="true" />

      {/* Top bar */}
      <section className="relative">
        <div className="hero-glow" />
        <div className="relative z-10 mx-auto max-w-7xl px-6 pt-10 pb-6 md:pt-14">
          <Link
            href="/"
            className="inline-flex items-center gap-1.5 text-xs text-muted transition hover:text-foreground"
          >
            <ArrowLeft className="h-3.5 w-3.5" />
            Back to builder
          </Link>
          <div className="mt-4 flex flex-wrap items-end justify-between gap-3">
            <div>
              <div className="mb-2 flex items-center gap-2 text-xs uppercase tracking-wide text-muted">
                <Video className="h-3.5 w-3.5 text-[var(--primary-light)]" />
                Gallery
              </div>
              <h1 className="text-4xl font-semibold tracking-tight md:text-5xl">
                All{" "}
                <span
                  className="text-accent-gradient"
                  style={{ fontStyle: "italic", fontWeight: 600 }}
                >
                  generations
                </span>
              </h1>
              <p className="mt-2 text-sm text-muted md:text-base">
                Every personalized video LeadFlow has rendered. Click any to
                play.
              </p>
            </div>
            <div className="font-mono text-xs text-muted">
              {entries.length} videos
            </div>
          </div>
        </div>
      </section>

      {/* Grid */}
      <section className="relative z-10 mx-auto max-w-7xl px-6 pb-24">
        <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
          {entries.map((g) => (
            <div
              key={g.id}
              className="glass glass-hover group flex flex-col overflow-hidden rounded-2xl text-left"
            >
              <div
                className="relative flex aspect-video items-center justify-center overflow-hidden"
                style={{
                  background: `radial-gradient(ellipse at 30% 30%, ${g.accent}55, transparent 65%), #0a0a0c`,
                }}
              >
                {g.videoUrl ? (
                  <video
                    src={g.videoUrl}
                    controls
                    autoPlay
                    muted
                    loop
                    playsInline
                    preload="metadata"
                    className="h-full w-full object-cover"
                  />
                ) : (
                  <>
                    <span
                      className="flex h-12 w-12 items-center justify-center rounded-full text-sm font-semibold text-white shadow-lg"
                      style={{ background: g.accent }}
                    >
                      {g.name
                        .split(" ")
                        .map((n) => n[0])
                        .join("")}
                    </span>
                    <span
                      className="absolute bottom-3 left-3 tag"
                      style={{ background: "rgba(255,255,255,0.92)" }}
                    >
                      0:30
                    </span>
                    <span className="absolute right-3 top-3 flex h-9 w-9 items-center justify-center rounded-full bg-white text-[#0a0a0c] opacity-0 shadow-lg transition group-hover:opacity-100">
                      <Play className="h-4 w-4 translate-x-[1px]" fill="currentColor" />
                    </span>
                  </>
                )}
              </div>
              <div className="flex flex-col gap-1 p-4">
                <div className="text-sm font-medium">{g.name}</div>
                <div className="text-xs text-muted">
                  {g.role} · {g.company}
                </div>
                <div className="mt-2 text-xs font-medium text-[var(--primary)]">
                  {g.stat}
                </div>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-[var(--border-token)] py-8 text-center text-xs text-muted">
        <div className="mx-auto max-w-7xl px-6">
          LeadFlow · Built for the HeyGen hackathon · May 2026
        </div>
      </footer>
    </main>
  );
}
